services:
  janus_config_factory:
    class: Janus\SSPIntegrationBundle\DependencyInjection\SSPConfigFactory

  janus_config:
    class: SimpleSAML_Configuration
    factory_service: janus_config_factory
    factory_method: create

  janus_session:
    class: SimpleSAML_Session
    factory_class: SimpleSAML_Session
    factory_method: getInstance