services:
  janus_config_factory:
    class: Janus\SSPIntegrationBundle\DependencyInjection\SSPConfigFactory
    arguments:    ["%kernel.environment%"]

  janus_config:
    class: SimpleSAML_Configuration
    factory_service: janus_config_factory
    factory_method: create

  janus_session:
    class: SimpleSAML_Session
    factory_class: SimpleSAML_Session
    factory_method: getInstance
    lazy: true

  authentication_provider:
    class: Janus\SSPIntegrationBundle\DependencyInjection\AuthenticationProvider
    arguments: [@janus_session, @janus_config]
