Acme\DemoBundle\Model\NoteCollection:
  exclusion_policy: ALL
  xml_root_name: notes
  properties:
    notes:
      expose: true
      type: array<Acme\DemoBundle\Model\Note>
      xml_list:
        inline: true
        entry_name: note
    offset:
      expose: true
      type: integer
      xml_attribute: true
    limit:
      expose: true
      type: integer
      xml_attribute: true
